version = 1

[[annotations]]
path = [
  ".dockerignore",
  ".gitignore",
  ".golangci.yml",
  ".markdownlint.json",
  ".github/renovate.json",
  ".github/workflows/ci.yaml",
  "Dockerfile",
  "Makefile",
  "hack/govulncheck.sh",
]
SPDX-FileCopyrightText = [
  "2025 Sidero Labs, Inc. <https://www.siderolabs.com/>",
  "2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>",
]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "cmd/kdev/common.go",
  "cmd/kdev/kind.go",
  "cmd/kdev/kind_test.go",
  "cmd/kdev/kubectl.go",
  "cmd/kdev/kubectl_test.go",
  "cmd/kdev/main.go",
  "cmd/kdev/tools.go",
  "cmd/kdev/tools_test.go",
  "cmd/kdev/version.go",
  "cmd/kdev/version_test.go",
  "go.mod",
  "go.sum",
  "internal/tool/cache.go",
  "internal/tool/cache_test.go",
  "internal/tool/config.go",
  "internal/tool/download.go",
  "internal/tool/download_test.go",
  "internal/tool/fs_helper.go",
  "internal/tool/http.go",
  "internal/tool/kind.go",
  "internal/tool/kind_test.go",
  "internal/tool/kubectl.go",
  "internal/tool/kubectl_test.go",
  "internal/tool/paths.go",
  "internal/tool/paths_test.go",
  "internal/tool/progress.go",
  "internal/tool/registry.go",
  "internal/tool/registry_test.go",
  "internal/tool/tool.go",
  "internal/tool/tool_test.go",
  "internal/util/format.go",
  "internal/util/format_test.go",
  "test/e2e/exec_test.go",
  "test/e2e/mock/tool.go",
]
SPDX-FileCopyrightText = "2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>"
SPDX-License-Identifier = "MPL-2.0"
